Release v0.1.16 - Python 3.12 Support
angelolab/pyFlowSOM pull request #19
Opened 2023-10-19 21:55 UTC by srivarra

**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Adds support for Python 3.12.

**How did you implement your changes**

N/A
**Remaining issues**

N/A

2023-10-19 22:39 UTC, ngreenwald requested changes
Will wait to hear from @JLrumberger about the timing of this one. If it doesn't interfere with the open PR addressing the versioning issues for macs, fine to move forward. However, if this could affect any of those changes, we should wait

2023-10-19 22:39 UTC, ngreenwald commented
Woops nevermind, wrong repo

2023-10-19 22:40 UTC, ngreenwald approved these changes

2023-10-20 17:04 UTC, camisowers approved these changes

2023-10-20 17:05 UTC, alex-l-kong approved these changes

2023-10-20 17:10 UTC, merged