Add initial repo config files
angelolab/pyFlowSOM pull request #2
Opened 2022-10-28 17:54 UTC by alex-l-kong

**What is the purpose of this PR?**

Closes #1. Provide a backbone config of `pyFlowSOM` for Travis CI integration.

**How did you implement your changes**

Use the templates provided in `ark-analysis` and `toffy`.

**Remaining issues**

@y2kbugger you'll probably need to tweak these config files for your particular project, feel free to leave review comments where needed.

2022-10-28 18:00 UTC, ngreenwald requested changes

2022-10-28 18:00 UTC, ngreenwald commented on requirements.txt
> +natsort>=8.1.0,<9
These are directly copied from `ark` I'm assuming? We should only include the bare minimum here

2022-10-28 18:35 UTC, alex-l-kong commented
Once we actually start putting code in this repo we can change the coverage back to failing under 45%.

2022-11-01 02:55 UTC, y2kbugger approved these changes

2022-11-01 03:04 UTC, merged